### ISSUE TITLE
Create sticker 

### ISSUE THREAD

**Issue by llrs** [llrs/BioCor#15]
https://github.com/Bioconductor/BiocStickers

**Comment by davidmasp** [comment]
did you have something in mind?

I was bored and I did this, if you wanna use it feel free

![image](https://user-images.githubusercontent.com/14033475/73681304-56ab0300-46be-11ea-8e81-194f8f3e200b.png)

**Comment by davidmasp** [comment]
well I can PR the svg/png I guess if you are interested. Note that this is based in my limited understanding of what the package does, but afaik it compares pathways no?

**Comment by llrs** [comment]
Many thanks!! No I haven't done anything on a while and wasn't sure how to design it. It looks great and on topic. I'll use it if you don't mind. Out of curiosity, how did you generate it?

**Comment by davidmasp** [comment]
inkscape

**Comment by davidmasp** [comment]
will PR, I have to check how people do this in bioc
